apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: agent-sandbox-identity
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
spec:
  identities:
    - "spiffe://{{ .Values.linkerd.trustDomain }}/ns/{{ .Values.namespace }}/sa/{{ .Values.serviceAccount.name }}"
